@startuml
left to right direction
skinparam packageStyle rectangle
actor Соискатель
actor Держатель
actor Администратор
actor Эксперт


Соискатель -up- (Заполнение формы)
Соискатель -left- (Просмотр формы)
Соискатель -down- (Просмотр решения)
Соискатель -right- (Просмотр статуса)
Соискатель -right- (Доработка формы)
Соискатель -left- (Получение уведомления о решении)

Администратор -up- (Проверка формы)
Администратор -down- (Изменение статуса)
Администратор -- (Просмотр)

Эксперт -up- (Получение уведомления о заявке)
Эксперт -right- (Просмотр формы)
Эксперт -right- (Просмотр экспертизы)
Эксперт -right- (Выставление оценки)

Держатель -down- (Получение уведомления об оценке)
Держатель -right- (Просмотр экспертизы)
Держатель -up- (Просмотр решения)
Держатель -right- (Просмотр формы)
Держатель -up- (Принятие решения)

(Просмотр) <|-- (Просмотр формы)
(Просмотр) <|-- (Просмотр экспертизы)
(Просмотр) <|-- (Просмотр решения)
(Просмотр) <|-- (Просмотр статуса)

(Доработка формы) .> (Проверка формы) : extend
(Изменение статуса) .-> (Просмотр статуса) : extend

(Заполнение формы) .> (Проверка формы) : include
(Заполнение формы) .> (Отправка формы) : include
(Проверка формы) .> (Отправка формы) : include
(Отправка формы) .> (Получение уведомления о заявке) : include
(Выставление оценки) .> (Получение уведомления об оценке) : include
(Выставление оценки) .> (Просмотр экспертизы) : include
(Просмотр экспертизы) .> (Принятие решения) : include
(Принятие решения) .> (Просмотр решения) : include
(Принятие решения) .-left-> (Получение уведомления о решении) : include

@enduml
