@startuml

class Пользователь {
 +Имя
 +Фамилия
 +Отчество
 +Id
 +ПросмотрЗаявки()
 +ПросмотрРешения()
}

class Соискатель {
    +Кол-воЗаявок
    +ЗаполнениеЗаявки()
    +ДоработкаЗаявки()
    +ОтправкаЗаявки()
    +ПросмотрСтатуса()
}

class Заявка {
    +Id
    +Описание
    +Наименование
}

class Новая {
}

class Существующая {
    +Статус
    +ДатаСоздания
}

class Эксперт {
    +Квалификация
    +ВыставлениеОценки()
    +ПросмотрОценки()
}

class Экспертиза {
    +Id
    +Наименование
    +Описание
    +Автор
}

class Держатель {
    +ПросмотрЭкспертизы()
    +ПринятиеРешения()
}

class Фонд {
    +Наименование
    +СуммаГранта
}

class Решение {
    +Id
    +Наименование
    +Описание
    +Автор
}

class Администратор {
    +ИзменениеСтатуса()
    +ПроверкаЗаявления()
    +ПросмотрСтатуса()
}


Соискатель --|> Пользователь
Эксперт --|> Пользователь
Держатель --|> Пользователь
Администратор --|> Пользователь

Новая --|> Заявка
Существующая --|> Заявка
Соискатель <.. Заявка

Эксперт <.. Экспертиза

Держатель ..* Фонд
Держатель <.. Решение

Администратор <..Заявка
Эксперт --o Заявка
Держатель --o Заявка

@enduml
