@startuml
participant Соискатель
activate Соискатель

Соискатель -> Форма: Заполнение формы
activate Форма

Форма --> Соискатель: Готовая форма
deactivate Форма

Соискатель -> Администратор: Отправка формы
activate Администратор

Администратор -> Форма: Проверка формы
activate Форма

Форма --> Администратор: Результат проверки
deactivate Форма

Администратор -> Эксперт: Отправка формы
deactivate Администратор
activate Эксперт

Эксперт -> Форма: Просмотр формы
activate Форма

Форма --> Эксперт: Результат просмотра
deactivate Форма

Эксперт -> Результат_оценки: Разработка результата
activate Результат_оценки

Результат_оценки --> Эксперт: Завершенный результат
deactivate Результат_оценки

Эксперт -> Держатель: Отправка результата оценки
deactivate Эксперт
activate Держатель

Держатель -> Результат_оценки: Просмотр результата оценки
activate Результат_оценки

Результат_оценки --> Держатель: Результат просмотра
deactivate Результат_оценки

Держатель -> Решение: Разработка решения
activate Решение

Решение --> Держатель: Итог разработки решения
deactivate Решение

Держатель -> Соискатель: Отправка решения
deactivate Держатель

Соискатель -> Решение: Просмотр решения
activate Решение

Решение --> Соискатель: Результат просмотра решения
deactivate Решение
deactivate Соискатель
@enduml