@startuml

|Соискатель|
start
:Заполнение формы;
:Отправка формы;

|Администратор|
:Проверка формы;
if (Корректно?) then (Да)
:Отправка формы;

|Эксперт|
:Просмотр формы;

else (Нет)
|Соискатель|
repeat :Доработка формы;
    :Отправка формы;
    |Администратор|
    :Проверка формы;
    repeat while (Коректно) is (Нет) not (Да)

:Отправка формы;
|Эксперт|
:Просмотр формы;

endif
:Выставление оценки;
fork
:Отправка оценки;
fork again
|Администратор|
:Изменение статуса;
|Держатель|
end fork
:Просмотр оценки;
:Принятие решения;
fork
:Отправка решения;
fork again
:Изменение статуса;
|Соискатель|
end fork
:Просмотр решения;
stop

@enduml
